# Generated by Django 4.0.10 on 2024-01-20 22:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0039_company_alter_customuser_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfficerTenantAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('officer', models.ForeignKey(help_text='The compliance officer', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Officer')),
                ('tenant', models.ForeignKey(help_text='The tenant assigned to the compliance officer', on_delete=django.db.models.deletion.CASCADE, to='home.client', verbose_name='Tenant')),
            ],
        ),
        migrations.CreateModel(
            name='Case',
            fields=[
                ('internalId', models.BigAutoField(primary_key=True, serialize=False)),
                ('externalId', models.UUIDField(default=uuid.uuid4, editable=False, help_text="The external case UUID that's safe to expose", unique=True, verbose_name='ID')),
                ('createdTs', models.DateTimeField(auto_now_add=True, help_text='The timestamp when a case was created', verbose_name='Created On')),
                ('lastActionTs', models.DateTimeField(blank=True, help_text='The last time the case was updated, status changed, etc.', null=True, verbose_name='Last Action On')),
                ('resourceTitle', models.CharField(help_text='The title of the resource associated with the case', max_length=255, verbose_name='Title')),
                ('resourceKey', models.CharField(help_text='The key/path of the resource/page associated with the case', max_length=255, verbose_name='Page')),
                ('type', models.CharField(choices=[('cms', 'CMS')], default='cms', help_text='The case type', max_length=255, verbose_name='Type')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], help_text='The current status of the case', max_length=255, verbose_name='Status')),
                ('notes', models.CharField(blank=True, help_text='Any additional notes on the case by the compliance officer', max_length=2048, null=True, verbose_name='Notes')),
                ('reviewedBy', models.ForeignKey(help_text='The compliance officer who reviewed the case', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Reviewed By')),
                ('tenant', models.ForeignKey(help_text='The tenant the case came from', on_delete=django.db.models.deletion.CASCADE, to='home.client', verbose_name='Tenant')),
            ],
        ),
        migrations.AddConstraint(
            model_name='officertenantassignment',
            constraint=models.UniqueConstraint(fields=('officer', 'tenant'), name='composite_pk'),
        ),
    ]
