# Generated by Django 4.0.10 on 2024-01-25 02:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='case',
            old_name='createdTs',
            new_name='created_ts',
        ),
        migrations.RenameField(
            model_name='case',
            old_name='internalId',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='case',
            old_name='notes',
            new_name='officer_notes',
        ),
        migrations.RenameField(
            model_name='case',
            old_name='resourceKey',
            new_name='resource_key',
        ),
        migrations.RenameField(
            model_name='case',
            old_name='resourceTitle',
            new_name='resource_title',
        ),
        migrations.RenameField(
            model_name='case',
            old_name='reviewedBy',
            new_name='reviewed_by',
        ),
        migrations.RenameField(
            model_name='case',
            old_name='lastActionTs',
            new_name='updated_ts',
        ),
        migrations.RemoveField(
            model_name='case',
            name='externalId',
        ),
        migrations.AddField(
            model_name='case',
            name='approved_ts',
            field=models.DateTimeField(default=None, null=True, verbose_name='Date Approved'),
        ),
        migrations.AddField(
            model_name='case',
            name='denied_ts',
            field=models.DateTimeField(default=None, null=True, verbose_name='Date Denied'),
        ),
        migrations.AddField(
            model_name='case',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text="The external case UUID that's safe to expose", unique=True, verbose_name='ID'),
        ),
    ]
