# Generated by Django 4.0.10 on 2024-02-01 04:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('compliance', '0002_rename_createdts_case_created_ts_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='reviewed_by',
            field=models.ForeignKey(default=None, help_text='The compliance officer who reviewed the case', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Reviewed By'),
        ),
        migrations.AlterField(
            model_name='case',
            name='updated_ts',
            field=models.DateTimeField(blank=True, default=None, help_text='The last time the case was updated, status changed, etc.', null=True, verbose_name='Last Action On'),
        ),
    ]
