# Generated by Django 4.0.10 on 2024-02-03 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0005_alter_case_resource_snapshot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='case',
            name='denied_ts',
        ),
        migrations.AddField(
            model_name='case',
            name='rejected_ts',
            field=models.DateTimeField(default=None, null=True, verbose_name='Date Rejected'),
        ),
    ]
