# Generated by Django 4.0.10 on 2024-02-06 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0006_remove_case_denied_ts_case_rejected_ts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='type',
            field=models.CharField(choices=[('cms', 'CMS'), ('crm', 'CRM')], default='cms', help_text='The case type', max_length=255, verbose_name='Type'),
        ),
    ]
