# Generated by Django 4.0.10 on 2024-02-02 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PostPageBlogCategory',
        ),
    ]
