# Generated by Django 4.0.10 on 2024-02-02 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_remove_postpage_tags'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PostPageTag',
        ),
    ]
