# Generated by Django 4.0.10 on 2024-02-02 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_delete_postpagetag'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PostPage',
        ),
    ]
