# Generated by Django 4.0.10 on 2024-02-02 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_delete_blogpage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlogCategory',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
