# Generated by Django 4.2.2 on 2023-11-22 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_delete_category_homepage_bg_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='bg_image',
        ),
    ]
