# Generated by Django 4.2.2 on 2023-11-22 22:28

from django.db import migrations
import django.utils.timezone
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0005_homepage_bg_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='body',
            field=wagtail.fields.StreamField([('heading', wagtail.blocks.CharBlock(form_classname='title')), ('paragraph', wagtail.blocks.RichTextBlock()), ('image', wagtail.images.blocks.ImageChooserBlock())], default=django.utils.timezone.now, use_json_field=True),
            preserve_default=False,
        ),
    ]
