# Generated by Django 4.2.2 on 2023-12-01 18:06

from django.db import migrations, models
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0008_homepage_sub_intro'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='intro_position',
            field=models.CharField(blank=True, choices=[('left', 'Left'), ('right', 'Right')], default='center', help_text='Select the position for the intro field.', max_length=6),
        ),
        migrations.AddField(
            model_name='homepage',
            name='talk_button_position',
            field=models.CharField(blank=True, choices=[('left', 'Left'), ('center', 'Center'), ('right', 'Right')], default='center', help_text='Select the position for the Talk button.', max_length=6),
        ),
        migrations.AddField(
            model_name='homepage',
            name='thank_you_text_position',
            field=models.CharField(blank=True, choices=[('left', 'Left'), ('center', 'Center'), ('right', 'Right')], default='center', help_text='Select the position for the thank_you_text field.', max_length=6),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='body',
            field=wagtail.fields.StreamField([('heading', wagtail.blocks.CharBlock(form_classname='title')), ('description', wagtail.blocks.RichTextBlock()), ('image_card', wagtail.blocks.StructBlock([('description', wagtail.blocks.RichTextBlock()), ('image', wagtail.images.blocks.ImageChooserBlock()), ('image_position', wagtail.blocks.ChoiceBlock(choices=[('left', 'Left'), ('right', 'Right')], help_text='Select the position of Image.', max_length=6))], classname='image-card'))], use_json_field=True),
        ),
    ]
