# Generated by Django 4.2.2 on 2023-12-10 22:32

from django.db import migrations, models
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks
import wagtailiconchooser.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0009_homepage_intro_position_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='body',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='thank_you_text_position',
        ),
        migrations.AddField(
            model_name='homepage',
            name='grid_card_column_count',
            field=models.CharField(blank=True, choices=[('2', '2 columns'), ('3', '3 columns'), ('4', '4 columns')], default='3', help_text='Select the number of columns for the grid (2-4).', max_length=6),
        ),
        migrations.AddField(
            model_name='homepage',
            name='services_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='services_expend_button',
            field=wagtail.fields.StreamField([('button_text', wagtail.blocks.CharBlock(label='Button Text', max_length=50, required=True))], blank=True, use_json_field=True, verbose_name='Expend Button'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='services_grid_card',
            field=wagtail.fields.StreamField([('cards', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('icon', wagtailiconchooser.blocks.IconChooserBlock(help_text='Choose an Service Icon.')), ('title', wagtail.blocks.CharBlock()), ('description', wagtail.blocks.TextBlock()), ('image', wagtail.images.blocks.ImageChooserBlock())])))], blank=True, use_json_field=True, verbose_name='Grid Card'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='services_heading',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='homepage',
            name='services_heading_sub',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='intro_position',
            field=models.CharField(blank=True, choices=[('left', 'Left'), ('right', 'Right')], default='right', help_text='Select the position for the intro field.', max_length=6),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='sub_intro',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
