# Generated by Django 4.2.2 on 2023-12-10 22:32

from django.db import migrations
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0011_homepage_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='form',
            field=wagtail.fields.StreamField([('image', wagtail.images.blocks.ImageChooserBlock(help_text='Choose an image for the form.')), ('heading', wagtail.blocks.CharBlock(help_text='Enter the heading for the content block')), ('text', wagtail.blocks.TextBlock(help_text='Enter the text for the content block')), ('elements', wagtail.blocks.StructBlock([('name', wagtail.blocks.CharBlock(help_text='Enter your full name', required=False)), ('email', wagtail.blocks.CharBlock(help_text='Enter your phone number', required=False)), ('password', wagtail.blocks.TextBlock(help_text='Enter your password', required=False)), ('address', wagtail.blocks.TextBlock(help_text='Enter your address', required=False)), ('post_code', wagtail.blocks.TextBlock(help_text='Enter your postal code', required=False))], blank=True, choices=[('left', 'Left'), ('right', 'Right')], default='right', help_text='Select the position for the intro field.'))], blank=True, use_json_field=True, verbose_name='form'),
        ),
    ]
