# Generated by Django 4.0.10 on 2024-01-23 00:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0013_alter_homepage_section'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HomePage',
        ),
    ]
