# Generated by Django 4.2.2 on 2023-08-21 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantoption',
            name='plan',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
