# Generated by Django 4.2.2 on 2023-09-06 21:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('adminapp', '0003_availabletime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availabletime',
            name='admin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='available', to=settings.AUTH_USER_MODEL),
        ),
    ]
