# Generated by Django 4.2.2 on 2023-09-15 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0005_demomeeting'),
    ]

    operations = [
        migrations.RenameField(
            model_name='demomeeting',
            old_name='creator',
            new_name='showcasher',
        ),
    ]
