# Generated by Django 4.2.2 on 2023-09-22 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0006_rename_creator_demomeeting_showcasher'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantoption',
            name='rtmp',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
