# Generated by Django 4.0.10 on 2024-01-23 00:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teampage', '0002_teampage_body'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TeamPage',
        ),
    ]
