# Generated by Django 4.2.2 on 2023-07-02 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_customuser_customer_id_pages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pages',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='pages',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
