# Generated by Django 4.2.2 on 2023-07-05 21:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_pages_created_at_alter_pages_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.TextField(max_length=255)),
                ('old_version', models.TextField(verbose_name='Old Version')),
                ('new_version', models.TextField(verbose_name='New Version')),
                ('submitter_note', models.TextField(default=None, max_length=1024, null=True, verbose_name='Note From Submitter')),
                ('approval_officer_note', models.TextField(default=None, max_length=1024, null=True, verbose_name='Note From Approval Officer')),
                ('approved_ts', models.DateTimeField(default=None, null=True, verbose_name='Date Approved')),
                ('denied_ts', models.DateTimeField(default=None, null=True, verbose_name='Date Denied')),
                ('status', models.TextField(default=None, null=True, verbose_name='Status')),
                ('updated_ts', models.DateTimeField(default=None, null=True, verbose_name='Submission Details Updated On')),
                ('created_ts', models.DateTimeField(auto_now=True, verbose_name='Date Submitted')),
                ('sub_view_old_url', models.TextField(default=None, max_length=1024, null=True)),
                ('sub_view_new_url', models.TextField(default=None, max_length=1024, null=True)),
                ('sub_screenshot_old_url', models.TextField(default=None, max_length=1024, null=True)),
                ('sub_screenshot_new_url', models.TextField(default=None, max_length=1024, null=True)),
                ('draft_file_endpoint', models.TextField(default=None, max_length=1024, null=True)),
                ('submitter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Slug',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('filename', models.CharField(max_length=200)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('image', models.CharField(default='', max_length=200)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_on'],
            },
        ),
    ]
