# Generated by Django 4.2.2 on 2023-07-06 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_submission_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='page',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='home.pages'),
        ),
    ]
