# Generated by Django 4.2.2 on 2023-07-06 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_submission_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='page',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='home.pages'),
        ),
    ]
