# Generated by Django 4.2.2 on 2023-07-14 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_alter_submission_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='checked',
            field=models.IntegerField(default=0),
        ),
    ]
