# Generated by Django 4.2.2 on 2023-07-26 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_schedulemeeting_aware_datetime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedulemeeting',
            name='end_time',
            field=models.TimeField(default=None),
        ),
        migrations.AlterField(
            model_name='schedulemeeting',
            name='time',
            field=models.TimeField(default=None),
        ),
    ]
