# Generated by Django 4.2.2 on 2023-08-23 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_customuser_approved_customuser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedulemeeting',
            name='status',
            field=models.CharField(default='', max_length=30),
        ),
    ]
