# Generated by Django 4.2.2 on 2023-08-27 16:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_schedulemeeting_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedulemeeting',
            name='enable_user_to_join',
            field=models.CharField(default='No', max_length=10),
        ),
        migrations.AlterField(
            model_name='schedulemeeting',
            name='creator',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='meeting', to=settings.AUTH_USER_MODEL),
        ),
    ]
