# Generated by Django 4.2.2 on 2023-08-31 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_schedulemeeting_lock_meeting'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='group',
            field=models.IntegerField(default=-1),
        ),
    ]
