# Generated by Django 4.2.2 on 2023-09-01 07:03
from django.contrib.auth.hashers import make_password
from django.db import migrations

from home.constants import APP_HOST, APP_DOMAIN
from home.models import Domain, Client
from home.utils import generate_short_uuid


def seed_data(apps, schema_editor):
    # Access models via apps['app_name']['ModelName']
    userModel = apps.get_model('home', 'CustomUser')


    # Create your initial records
    customer_id = generate_short_uuid()
    userModel.objects.create(email='gomak0887@gmail.com', username='gomak0887@gmail.com', password=make_password("admin123"),
                             role=2, customer_id=customer_id, group=1)

class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_customuser_group'),
    ]

    operations = [
        migrations.RunPython(seed_data)
    ]
