# Generated by Django 4.2.2 on 2023-09-03 16:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_auto_20230901_0203'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedulemeeting',
            name='partner',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schedule_meeting', to=settings.AUTH_USER_MODEL),
        ),
    ]
