# Generated by Django 4.2.2 on 2023-09-27 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0030_alter_schedulemeeting_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='calendar_id',
            field=models.CharField(default='', max_length=255),
        ),
    ]
