# Generated by Django 4.2.2 on 2023-09-29 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0031_customuser_calendar_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='nylas_access_token',
            field=models.CharField(default='', max_length=255),
        ),
    ]
