# Generated by Django 4.2.2 on 2023-10-12 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0032_customuser_nylas_access_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='pages',
            name='level',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='pages',
            name='parent_id',
            field=models.IntegerField(default=0),
        ),
    ]
