# Generated by Django 4.2.2 on 2023-10-13 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0033_pages_level_pages_parent_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='pages',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
