# Generated by Django 4.2.2 on 2023-10-25 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0036_tenantuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='domain_url',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
