# Generated by Django 4.2.2 on 2023-11-21 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0037_customuser_domain_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='cms_flag',
            field=models.CharField(default='', max_length=200),
        ),
    ]
