# Generated by Django 4.0.10 on 2024-01-21 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0039_company_alter_customuser_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='cms_flag',
        ),
    ]
