# Generated by Django 4.0.10 on 2024-02-05 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0040_remove_customuser_cms_flag'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='enable_self_managed_compliance',
            field=models.BooleanField(default=False, help_text='Whether a tenant admin can approve/reject compliance cases without the need for a compliance officer', verbose_name='Enable Self-Managed Compliance'),
        ),
    ]
