# Generated by Django 4.0.10 on 2024-02-05 18:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0041_client_enable_self_managed_compliance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meetings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('user_email', models.CharField(blank=True, max_length=255, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('date', models.DateField(blank=True, default=None, null=True)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('duration', models.DurationField(blank=True, null=True)),
                ('created_on', models.DateField(auto_now_add=True)),
                ('is_hidden', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True, null=True)),
                ('meeting_type', models.IntegerField(choices=[(1, 'Personal Meeting'), (2, 'Consultation')], default=1)),
                ('event_link', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_meetings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
