# Generated by Django 4.0.10 on 2024-02-17 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0045_remove_userprofile_user_delete_booking_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedulemeeting',
            name='email',
            field=models.CharField(max_length=254, null=True),
        ),
    ]
