# Generated by Django 4.0.10 on 2024-02-18 17:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0046_alter_schedulemeeting_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='The event title', max_length=64, verbose_name='Title')),
                ('slug', models.CharField(help_text='The slug, used to construct the full event type URL for booking', max_length=64, verbose_name='Slug')),
                ('description', models.CharField(help_text='The event description', max_length=2048, verbose_name='Description')),
                ('duration_minutes', models.IntegerField(help_text='The event type duration in minutes,', verbose_name='Duration Minutes')),
                ('location', models.CharField(choices=[('virtual', 'Virtual Meeting'), ('phone', 'Phone Call'), ('in_person', 'In-Person Meeting')], help_text='The type of location or setting the meeting will take place in', max_length=255, verbose_name='Location')),
                ('is_hidden', models.BooleanField(default=False, help_text="Whether the event type is hidden from the user's public event listing page", verbose_name='Is Hidden?')),
                ('created_ts', models.DateTimeField(auto_now_add=True, help_text='The event type creation timestamp', verbose_name='Created On')),
                ('user', models.ForeignKey(help_text='The internal user that the event type applies to or was created by', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
        migrations.CreateModel(
            name='EventBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_ts', models.DateTimeField(help_text='The timestamp of when the event begins. This includes both date and time.', verbose_name='Start Timestamp')),
                ('end_ts', models.DateTimeField(help_text='The timestamp when the event ends. This includes both date and time.', verbose_name='End Timestamp')),
                ('scheduler_name', models.CharField(help_text='The name of the person who booked the meeting', max_length=200, verbose_name='Scheduler Name')),
                ('scheduler_email', models.CharField(help_text='The email of the person who booked the meeting', max_length=254, verbose_name='Schedule Email')),
                ('created_ts', models.DateTimeField(auto_now_add=True, help_text='The event booking creation timestamp', verbose_name='Created On')),
                ('event_type', models.ForeignKey(help_text='The associated event type', on_delete=django.db.models.deletion.CASCADE, to='home.eventtype', verbose_name='Event Type')),
            ],
        ),
        migrations.AddConstraint(
            model_name='eventtype',
            constraint=models.UniqueConstraint(fields=('user', 'slug'), name='user_slug_unique_key'),
        ),
    ]
