# Generated by Django 4.0.10 on 2024-02-28 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0048_eventbooking_meeting_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='secondary_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
