# Generated by Django 4.0.10 on 2024-03-29 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0049_customuser_secondary_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='personal_meeting_link',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
