# Generated by Django 4.2.2 on 2023-10-09 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcms', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserPage',
        ),
    ]
