# Generated by Django 4.2.2 on 2023-11-29 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcms', '0002_delete_userpage'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminLogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='admin_logos')),
            ],
            options={
                'verbose_name_plural': 'Admin Logos',
            },
        ),
    ]
