# Generated by Django 4.0.10 on 2024-01-23 00:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcms', '0004_aboutpage_contactpage_eventtypepage_homepage_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ThemeSettings',
        ),
    ]
