# Generated by Django 4.0.10 on 2024-01-23 00:44

from django.db import migrations, models
import django.db.models.deletion
import wagtail_color_panel.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0025_alter_image_file_alter_rendition_file'),
        ('wagtailcms', '0005_delete_themesettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThemeSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_theme', models.CharField(choices=[('theme1', 'Theme 1'), ('theme2', 'Theme 2'), ('theme3', 'Theme 3')], default='theme1', max_length=255)),
                ('headline_font', models.CharField(choices=[('Arial', 'Arial'), ('Helvetica', 'Helvetica'), ('Times New Roman', 'Times New Roman'), ('Georgia', 'Georgia'), ('Verdana', 'Verdana'), ('Roboto', 'Roboto'), ('Open Sans', 'Open Sans'), ('Lato', 'Lato'), ('Roboto Slab', 'Roboto Slab'), ('Cabin', 'Cabin')], default='', max_length=255)),
                ('headline_size', models.CharField(choices=[('14px', 'Small'), ('18px', 'Medium'), ('22px', 'Large')], default='', max_length=255)),
                ('paragraph_font', models.CharField(choices=[('Arial', 'Arial'), ('Helvetica', 'Helvetica'), ('Times New Roman', 'Times New Roman'), ('Georgia', 'Georgia'), ('Verdana', 'Verdana'), ('Roboto', 'Roboto'), ('Open Sans', 'Open Sans'), ('Lato', 'Lato'), ('Roboto Slab', 'Roboto Slab'), ('Cabin', 'Cabin')], default='', max_length=255)),
                ('paragraph_size', models.CharField(choices=[('12px', 'Small'), ('14px', 'Medium'), ('18px', 'Large')], default='', max_length=255)),
                ('color', wagtail_color_panel.fields.ColorField(default='#000000', max_length=7)),
                ('color2', wagtail_color_panel.fields.ColorField(default='#001', max_length=7)),
                ('background_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
