# Generated by Django 4.0.10 on 2024-01-23 01:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcms', '0006_themesettings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactpage',
            name='page_ptr',
        ),
        migrations.RemoveField(
            model_name='eventtypepage',
            name='page_ptr',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='page_ptr',
        ),
        migrations.RemoveField(
            model_name='locationspage',
            name='page_ptr',
        ),
        migrations.RemoveField(
            model_name='servicespage',
            name='page_ptr',
        ),
        migrations.RemoveField(
            model_name='teampage',
            name='page_ptr',
        ),
        migrations.RemoveField(
            model_name='themesettings',
            name='background_image',
        ),
        migrations.DeleteModel(
            name='AboutPage',
        ),
        migrations.DeleteModel(
            name='ContactPage',
        ),
        migrations.DeleteModel(
            name='EventTypePage',
        ),
        migrations.DeleteModel(
            name='HomePage',
        ),
        migrations.DeleteModel(
            name='LocationsPage',
        ),
        migrations.DeleteModel(
            name='ServicesPage',
        ),
        migrations.DeleteModel(
            name='TeamPage',
        ),
        migrations.DeleteModel(
            name='ThemeSettings',
        ),
    ]
