# Generated by Django 4.0.10 on 2024-01-23 01:31

from django.db import migrations
import wagtail_color_panel.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcms', '0010_themesettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='themesettings',
            name='color',
            field=wagtail_color_panel.fields.ColorField(max_length=7),
        ),
        migrations.AlterField(
            model_name='themesettings',
            name='color2',
            field=wagtail_color_panel.fields.ColorField(max_length=7),
        ),
    ]
