# Generated by Django 4.0.10 on 2024-01-23 03:37

from django.db import migrations
import wagtail_color_panel.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcms', '0012_remove_themesettings_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='themesettings',
            name='color',
            field=wagtail_color_panel.fields.ColorField(default=1, max_length=7),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='themesettings',
            name='color2',
            field=wagtail_color_panel.fields.ColorField(default=1, max_length=7),
            preserve_default=False,
        ),
    ]
