# Generated by Django 4.0.10 on 2024-01-30 20:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0025_alter_image_file_alter_rendition_file'),
        ('wagtailcms', '0027_blogindexpage_blogpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogindexpage',
            name='cover_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blog_index_cover_image', to='wagtailimages.image'),
        ),
    ]
