# Generated by Django 4.0.10 on 2024-02-02 20:12

from django.db import migrations
import wagtail_color_panel.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcms', '0030_alter_aboutpage_body_alter_contactpage_body_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='themesettings',
            name='color',
        ),
        migrations.RemoveField(
            model_name='themesettings',
            name='color2',
        ),
        migrations.AddField(
            model_name='themesettings',
            name='footer_color',
            field=wagtail_color_panel.fields.ColorField(default='#011A41', max_length=7),
        ),
        migrations.AddField(
            model_name='themesettings',
            name='heading_color',
            field=wagtail_color_panel.fields.ColorField(default='#011A41', max_length=7),
        ),
        migrations.AddField(
            model_name='themesettings',
            name='paragraph_color',
            field=wagtail_color_panel.fields.ColorField(default='#555555', max_length=7),
        ),
        migrations.AddField(
            model_name='themesettings',
            name='primary_color',
            field=wagtail_color_panel.fields.ColorField(default='#355EFC', max_length=7),
        ),
    ]
