# Generated by Django 4.0.10 on 2024-02-05 00:50

from django.db import migrations
import wagtail_color_panel.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcms', '0033_privacypolicypage'),
    ]

    operations = [
        migrations.AddField(
            model_name='themesettings',
            name='cta_color',
            field=wagtail_color_panel.fields.ColorField(default='#355EFC', max_length=7),
        ),
    ]
