# Generated by Django 4.0.10 on 2024-03-05 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcms', '0037_rename_address_websitesettings_display_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='websitesettings',
            name='google_analytics_key',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
