# Generated by Django 4.0.10 on 2024-03-06 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcms', '0039_websitesettings_ms_clarity_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventpage',
            name='end_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='eventpage',
            name='show_register_button',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='eventpage',
            name='start_date',
            field=models.DateTimeField(null=True),
        ),
    ]
