# Generated by Django 4.0.10 on 2024-03-08 20:58

from django.db import migrations
import wagtail.blocks
import wagtail.fields
import wagtailstreamforms.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcms', '0040_eventpage_end_date_eventpage_show_register_button_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventpage',
            name='register_form',
            field=wagtail.fields.StreamField([('form', wagtail.blocks.StructBlock([('form', wagtailstreamforms.blocks.FormChooserBlock()), ('form_action', wagtail.blocks.CharBlock(help_text='The form post action. "" or "." for the current page or a url', required=False)), ('form_reference', wagtailstreamforms.blocks.InfoBlock(help_text='This form will be given a unique reference once saved', required=False))]))], blank=True, null=True, use_json_field=True),
        ),
    ]
