# Generated by Django 4.0.10 on 2024-03-30 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcms', '0042_alter_eventpage_intro_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventpage',
            name='event_id',
            field=models.IntegerField(null=True),
        ),
    ]
