# Generated by Django 4.0.10 on 2024-04-01 21:03

from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcms', '0043_eventpage_event_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='themesettings',
            name='global_style_and_scripts_end',
            field=wagtail.fields.StreamField([('raw_html', wagtail.blocks.RawHTMLBlock(required=True))], blank=True, help_text="Don't forget to use <style></style> or <script></script> tags", null=True, use_json_field=True),
        ),
        migrations.AddField(
            model_name='themesettings',
            name='global_style_and_scripts_head',
            field=wagtail.fields.StreamField([('raw_html', wagtail.blocks.RawHTMLBlock(required=True))], blank=True, help_text="Don't forget to use <style></style> or <script></script> tags", null=True, use_json_field=True),
        ),
    ]
