from .about import *
from .blog_pages import *
from .contact import *
from .default_page import *
from .event_type import *
from .homepage import *
from .locations import *
from .privacy_policy import *
from .services import *
from .team_page import *
from .theme_settings import *
from .website_settings import *
